# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89730cf0c2ccd799e6fd1b03f3043d4a108d28a3ec5315d2befcbd7a9f709deac7a1ba5767718a2c57850d29a2b02f4005f4b29ad7ce4e8af5f199a7a1efe36b

test:
  secret_key_base: aa9ce0eec800d949a6a0d931741990e4f8b640493c6c6ddd0aca9d9d669b7c7a9d722aea42238a72a524b6a9f5ceb3e939ee0508f1fae59f4de67a957c299c26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
