Category.create!([
  {name: "Proqramlar", deleted: false, slug: "proqramlar"}
])

Question.create!([
  {title: "Nə etməli?", answer: "Lenini oxumalı", slug: "ne-etmeli"},
  {title: "Lorem ipsum dolor sit amet, consectetur adipiscing elit?", answer: "Lorem ipsum dolor sit amet, consectetur adipiscing elit?<br>", slug: "lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit"},
  {title: "Aenean consequat lorem ut felis ullamcorper?", answer: "<div id=\"collapseNine\" class=\"panel-collapse collapse in\" style=\"\">Anim pariatur cliche reprehenderit, enim\r\n eiusmod high life accusamus terry richardson ad squid. 3 wolf moon \r\nofficia aute, non cupidatat skateboard dolor brunch. Food truck quinoa \r\nnesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a \r\nbird on it squid single-origin coffee nulla assumenda shoreditch et. \r\nNihil anim keffiyeh helvetica, craft beer labore wes anderson cred \r\nnesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. \r\nLeggings occaecat craft beer farm-to-table, raw denim aesthetic synth \r\nnesciunt you probably haven't heard of them accusamus labore sustainable\r\n VHS. Lorem again.</div>", slug: "aenean-consequat-lorem-ut-felis-ullamcorper"},
  {title: "Curabitur eget leo at velit imperdiet varius. In eu ipsum vitae velit congue?", answer: "<div id=\"collapseSeven\" class=\"panel-collapse collapse in\" style=\"\">Anim pariatur cliche reprehenderit, enim\r\n eiusmod high life accusamus terry richardson ad squid. 3 wolf moon \r\nofficia aute, non cupidatat skateboard dolor brunch. Food truck quinoa \r\nnesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a \r\nbird on it squid single-origin coffee nulla assumenda shoreditch et. \r\nNihil anim keffiyeh helvetica, craft beer labore wes anderson cred \r\nnesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. \r\nLeggings occaecat craft beer farm-to-table, raw denim aesthetic synth \r\nnesciunt you probably haven't heard of them accusamus labore sustainable\r\n VHS.\r\n                            \r\n                        </div>", slug: "curabitur-eget-leo-at-velit-imperdiet-varius-in-eu-ipsum-vitae-velit-congue"}
])

Article.create!([
  {title: " Programme invitation", image: "image/upload/v1499616827/programme-invitation.jpg", body: "<p><strong class=\" elm-has-own-text\">Hvordan bekjempe voldelig \r\nekstremisme og terror uten å radere grunnleggende friheter som \r\nytringsfrihet og retten til privatliv, har blitt en av vår tids største \r\nutfordringer. I terrorfryktens tid er det ofte maktens språk at borgerne\r\n må være villig til å gi opp noen av sine individuelle friheter for at \r\nvi som samfunn skal kunne føle oss trygge. Hvilke konsekvenser får det \r\nfor ytrings- og mediefriheten og vår rett til informasjon, på kort og \r\nlang sikt? </strong></p>\r\n\r\n<p class=\" elm-has-own-text\">Ingvil Conradi Andersen har nylig avsluttet\r\n et toårig opphold i Wien hvor hun har vært sekondert av NORDEM som \r\nseniorrådgiver ved kontoret til OSSEs representant for frie medier. \r\nGjennom arbeidet har hun erfart at anti-terrorlovgivning, overvåkning og\r\n andre nasjonale sikkerhetstiltak i økende grad innskrenker ytrings- og \r\nmediefriheten og skaper vanskeligere arbeidsvilkår for journalister i \r\nhele OSSE-regionen. I lys av dette vil hun blant annet snakke om</p>\r\n\r\n<p class=\" elm-has-own-text\">Hvilke påvirkningsmuligheter har <a href=\"http://www.osce.org/fom/282521\">OSSEs representant for frie medier</a> i lys av sitt mandat?</p>\r\n\r\n<p class=\" elm-has-own-text\">Hvilke internasjonale standarder og \r\nforpliktelser gjelder? På hvilken måte skaper mangelen på internasjonale\r\n anerkjente definisjoner av begreper som \"voldelig ekstremisme\", \r\n\"terror\" og \"radikalisering\" problemer?</p>\r\n\r\n<p class=\" elm-has-own-text\">Hva er hovedutfordringene for ytrings- og mediefriheten i en anti-terrorkontekst?</p>\r\n\r\n<p class=\" elm-has-own-text\">Hvilken rolle skal sosiale medier, søkemotorer og andre nettportaler spille i kampen mot terror?</p>\r\n\r\n<p class=\" elm-has-own-text\">Conradi Andersen er jurist med \r\nytringsfrihet og medieregulering som spesiale. Hun jobber i dag som \r\nseniorrådgiver i Kulturdepartementets medieavdeling, og har tidligere \r\nbakgrunn som advokat, dommerfullmektig og fra arbeid i Medietilsynet.</p>\r\n\r\n<p class=\" elm-has-own-text\">Organisert av NORDEM</p>\r\n\r\n<p><strong class=\" elm-has-own-text\">Vennligst meld deg på <a href=\"https://nettskjema.uio.no/answer/78066.html\">her </a>.</strong></p>\r\n\r\n<p class=\" elm-has-own-text\">Velkommen!</p>", author_id: 4, category_id: 5, deleted: false, slug: "programme-invitation"},
  {title: "MA Conflict Studies and Human Rights", image: nil, body: "<p>During recent decades, the world has witnessed a multitude of armed \r\nconflicts that have affected people all over the globe. Millions of \r\npeople have been killed and many more have been forced to flee because \r\nof war. Societies have been disrupted, and economies severely affected. \r\nArmed conflicts continue to threaten the lives, livelihood, and future \r\nof millions of people. The Master’s programme in Conflict Studies and \r\nHuman Rights focuses on studying and engaging contemporary conflict and \r\nassociated human rights issues.</p>\r\n<p>Current realities have forced the international community to address \r\ncontemporary conflicts with a combination of military, humanitarian, \r\npolitical, economic, and development-related measures. So far, however, \r\nthe record of conflict management has been mixed. Notwithstanding \r\nincidental successes, there have been several less successful attempts \r\nand even outright failures.</p>\r\n<p>This highlights the need to better understand the nature of \r\ncontemporary conflict, and to ground this understanding in empirical \r\nresearch and theoretical explanations. Apart from a better understanding\r\n of conflict per se, there is also a lack of trained personnel in this \r\nrapidly growing professional field. It is against this backdrop that \r\nUtrecht University offers a one-year selective international Master’s \r\nprogramme in Conflict Studies and Human Rights.</p>\r\n<p>For more information on this programme and on how to enroll, see <a href=\"http://www.uu.nl/university/masters/NL/conflictstudies/Pages/default.aspx?refer=/NL/Informatie/master/conflictstudies\">here</a>.</p>", author_id: 3, category_id: 5, deleted: false, slug: "ma-conflict-studies-and-human-rights"}
])
